// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7NQ7HpsN_OSj81gH9zm17k0VxT6IHhOg',
    appId: '1:427646659327:web:2452553efdd9562e763aca',
    messagingSenderId: '427646659327',
    projectId: 'kytyyony-6e012',
    authDomain: 'kytyyony-6e012.firebaseapp.com',
    storageBucket: 'kytyyony-6e012.appspot.com',
    measurementId: 'G-FK876J0F3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjmDHa088LyaieSDSiCAFNQO-zOf7y3x8',
    appId: '1:427646659327:android:b52d68c9c620f797763aca',
    messagingSenderId: '427646659327',
    projectId: 'kytyyony-6e012',
    storageBucket: 'kytyyony-6e012.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChsyF1r530Z0ztpZclEOeQvUmvCdQm9m8',
    appId: '1:427646659327:ios:1c2c866e701422f0763aca',
    messagingSenderId: '427646659327',
    projectId: 'kytyyony-6e012',
    storageBucket: 'kytyyony-6e012.appspot.com',
    iosBundleId: 'org.eurekamps.kyty',
  );
}
